#this is the makefile that will be used by the make build utility for the execution of the structure program in this directory


firstStructure: firstStructure.o
	gcc -o firstStructure firstStructure.o

firstStructure.o: firstStructure.c
	gcc -c firstStructure.c
